version: '3.8'

services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.5
    hostname: wazuh-indexer
    restart: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "INDEXER_USERNAME=admin"
      - "INDEXER_PASSWORD=SecretPassword"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.5
    hostname: wazuh-dashboard
    restart: always
    ports:
      - "443:5601"
    depends_on:
      - wazuh-indexer
    environment:
      - "INDEXER_URL=https://wazuh-indexer:9200"
      - "INDEXER_USERNAME=admin"
      - "INDEXER_PASSWORD=SecretPassword"
      - "DASHBOARD_USERNAME=admin"
      - "DASHBOARD_PASSWORD=SecretPassword"
    volumes:
      - ./ssl:/etc/ssl/wazuh

  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.5
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514"
      - "1515:1515"
      - "55000:55000"
    depends_on:
      - wazuh-indexer
    volumes:
      - wazuh-manager-etc:/var/ossec/etc
      - wazuh-manager-data:/var/ossec/var/multigroups
      - wazuh-manager-logs:/var/ossec/logs
      - wazuh-manager-queue:/var/ossec/queue
      - wazuh-manager-var:/var/ossec/var
      - ./custom-rules:/var/ossec/etc/rules:ro

volumes:
  wazuh-indexer-data:
  wazuh-manager-etc:
  wazuh-manager-data:
  wazuh-manager-logs:
  wazuh-manager-queue:
  wazuh-manager-var: